---
- hosts: local
  connection: local
  tasks:
    - name: Install homebrew cask packages
      homebrew_cask:
        name: "{{ item }}"
        state: present
      with_items:
        - virtualbox
        - virtualbox-extension-pack
